[package]
name = "advent-of-code-25"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/BB223/adventofcode25"
authors = ["BB223"]

[dependencies]
itertools = "0.14.0"
rayon = "1.11.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
